// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybdO1Sl3-zt_VrkkilE5UmZkR-J101BA',
    appId: '1:283843330054:web:4ebc86fb203b840197c387',
    messagingSenderId: '283843330054',
    projectId: 'yemeksiparis-150a0',
    authDomain: 'yemeksiparis-150a0.firebaseapp.com',
    storageBucket: 'yemeksiparis-150a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAyJdUMuEd1RlaFjSZQ17Ex0GAQmVsOM',
    appId: '1:283843330054:android:bedf97013aac977497c387',
    messagingSenderId: '283843330054',
    projectId: 'yemeksiparis-150a0',
    storageBucket: 'yemeksiparis-150a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIH_Jm78UljlGqYZ88a3F8YOMir1tkdB4',
    appId: '1:283843330054:ios:6ec2c5b8211d97d397c387',
    messagingSenderId: '283843330054',
    projectId: 'yemeksiparis-150a0',
    storageBucket: 'yemeksiparis-150a0.firebasestorage.app',
    iosClientId: '283843330054-2ab7c49st4og2bbnrtmnngpflc341e64.apps.googleusercontent.com',
    iosBundleId: 'com.example.yemeksiparis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIH_Jm78UljlGqYZ88a3F8YOMir1tkdB4',
    appId: '1:283843330054:ios:6ec2c5b8211d97d397c387',
    messagingSenderId: '283843330054',
    projectId: 'yemeksiparis-150a0',
    storageBucket: 'yemeksiparis-150a0.firebasestorage.app',
    iosClientId: '283843330054-2ab7c49st4og2bbnrtmnngpflc341e64.apps.googleusercontent.com',
    iosBundleId: 'com.example.yemeksiparis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCybdO1Sl3-zt_VrkkilE5UmZkR-J101BA',
    appId: '1:283843330054:web:7f0792322a67723d97c387',
    messagingSenderId: '283843330054',
    projectId: 'yemeksiparis-150a0',
    authDomain: 'yemeksiparis-150a0.firebaseapp.com',
    storageBucket: 'yemeksiparis-150a0.firebasestorage.app',
  );
}
